/*
 * Collin Koldoff
 * 10/29/2020
 */

package APCS;

import java.util.Scanner;

public class Magic8Ball {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in); // Scanner for loop
        boolean running = true;
        final String[] OUTPUT = 
        {"It is certain", 
        "It is decidedly so", 
        "Most likely", 
        "My reply is no", 
        "My sources say no", 
        "Outlook not so good", 
        "Outlook good", 
        "Reply hazy, try again"}; // List of all responses
        while (running) { // Uses a variable to suppress resource leak in Scanner in
            System.out.println(OUTPUT[getRandomNumber()]); // Prints the response at the index that is generated by the getResponse class
            // Or a bunch of if statements or a switch case, but this is easier

            System.out.println("\nPress enter to generate a new response");
            in.nextLine(); // Pauses until enter is pressed
        }
        in.close(); // Suppresses Scanner in resource leak
    }

    private static int getRandomNumber() {
        return (int) (Math.random() * 8); // Generates a random number between 1 and 7 inclusive
    }
}
